name: athena_utils
description: >-
  Util common package for Athena SQL and its CLI
version: 1.0.2
homepage: https://docs.athena-sql.dev/utils/
repository: https://github.com/athena-sql/athena_sql/tree/master/packages/athena_utils

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  file: ^7.0.0
  meta: ^1.9.1
  yaml: ^3.1.2
