name: athena_utils
description: >-
  Util common package for Athena SQL and its CLI
version: 1.0.4
homepage: https://docs.athena-sql.dev/utils/
repository: https://github.com/athena-sql/athena_sql/tree/master/packages/athena_utils

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.9
dependencies:
  file: ^7.0.1
  meta: ^1.16.0
  yaml: ^3.1.2
