name: athena_sql

packages:
  - packages/*


scripts:
  lint:all:
    run: melos run analyze && melos run format
    description: Run all static analysis checks.
  test:coverage:
    run: dart pub global run coverage:test_with_coverage -b -f -- -j 1
    description: Run test with coverage.
    exec:
      concurrency: 1
    packageFilters:
      dirExists: test
  cache-source:
    run: melos exec -- "mkdir -p '$PUB_CACHE/hosted/pub.dev/\$MELOS_PACKAGE_NAME-\$MELOS_PACKAGE_VERSION' && cp -rf '\$MELOS_PACKAGE_PATH'/* '$PUB_CACHE/hosted/pub.dev/\$MELOS_PACKAGE_NAME-\$MELOS_PACKAGE_VERSION'"
  tighten:
    exec: dart pub upgrade --tighten
