name: athena_postgres
description: >-
  Dart PostgreSQL query builder, expressive and user-friendly API to build and manage SQL queries in your Dart projects.
version: 1.0.13
homepage: https://docs.athena-sql.dev/postgres/
repository: https://github.com/athena-sql/athena_sql/tree/master/packages/athena_postgres/

topics:
  - sql
  - postgres

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  athena_sql: ^1.1.8
  path: ^1.9.1
  postgres: ^3.4.4

dev_dependencies:
  docker_process: ^1.3.2
  lints: ^5.0.0
  test: ^1.25.9
