name: athena_postgres
description: >-
  Dart PostgreSQL query builder, expressive and user-friendly API to build and manage SQL queries in your Dart projects.
version: 1.0.13
homepage: https://docs.athena-sql.dev/postgres/
repository: https://github.com/athena-sql/athena_sql/tree/master/packages/athena_postgres/

topics:
  - sql
  - postgres

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  path: ^1.8.3
  postgres: ^3.0.1
  athena_sql: ^1.1.8

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  docker_process: ^1.3.1
