name: athena_mysql
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  path: ^1.8.3
  athena_sql:
    path: ../athena_sql
  mysql_client: ^0.0.27

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  docker_process: ^1.3.1
