name: athena_sql
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  collection: ^1.17.1
  athena_utils:
    path: ../athena_utils

dev_dependencies:
  lints: ^2.0.0
  sqlparser: ^0.28.1
  test: ^1.21.0
  mockito: ^5.4.0
  build_runner: ^2.3.3
