name: athena_sql
description: >-
  Dart SQL query builder, expressive and user-friendly API to build and manage SQL queries in your Dart projects.
version: 1.1.8
homepage: https://docs.athena-sql.dev/
repository: https://github.com/athena-sql/athena_sql/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: any
  athena_utils: ^1.0.4

dev_dependencies:
  lints: ^5.0.0
  test: ^1.25.9
  mockito: ^5.4.4
  build_runner: ^2.4.13
