name: athena_sql
description: >-
  Dart SQL query builder, expressive and user-friendly API to build and manage SQL queries in your Dart projects.
version: 1.1.4
homepage: https://docs.athena-sql.dev/
repository: https://github.com/athena-sql/athena_sql/

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.17.1
  athena_utils: ^1.0.3

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  mockito: ^5.4.0
  build_runner: ^2.3.3
