name: athena_migrate
description: Athena SQL migration tool
version: 1.0.0
homepage: https://athena-sql.gitbook.io/
repository: https://github.com/athena-sql/migration/

environment:
  sdk: '>=2.19.0 <4.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  args: ^2.4.1
  intl: ^0.18.0
  path: ^1.8.3
  yaml: ^3.1.1
  athena_utils: ^1.0.0
  collection: ^1.17.1