name: athena_migrate
description: Athena SQL migration tool
version: 1.1.0
homepage: https://docs.athena-sql.dev/migration/
repository: https://github.com/athena-sql/athena_sql/tree/master/packages/athena_migrate

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.4.13
  lints: ^5.0.0
  mockito: ^5.4.4
  test: ^1.25.9
dependencies:
  args: ^2.6.0
  intl: ^0.20.1
  path: ^1.9.1
  yaml: ^3.1.2
  athena_utils: ^1.1.0
  collection: ^1.19.1
  clock: ^1.1.2
executables:
  athena_migrate: