name: athena_migrate
description: Athena SQL migration tool
version: 1.0.3
homepage: https://docs.athena-sql.dev/migration/
repository: https://github.com/athena-sql/athena_sql/tree/master/packages/athena_migrate

environment:
  sdk: '>=3.0.0 <4.0.0'

dev_dependencies:
  build_runner: ^2.3.0
  lints: ^2.0.0
  mockito: ^5.4.0
  test: ^1.21.0
dependencies:
  args: ^2.4.1
  intl: ^0.18.0
  path: ^1.8.3
  yaml: ^3.1.1
  athena_utils: ^1.0.2
  collection: ^1.17.1
  clock: ^1.1.1
executables:
  athena_migrate: