name: Dart CI

on: [push, workflow_dispatch]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                sdk: [2.17.0, stable, beta, dev]
            fail-fast: false
        steps:
        - uses: actions/checkout@v3
        - uses: dart-lang/setup-dart@v1
          with:
            sdk: ${{ matrix.sdk }}

        - name: Print DART_HOME
          run: echo "Dart SDK installed in $DART_HOME"

        - name: Verify code formatting
          run: dart format --output none --set-exit-if-changed 

        - name: Install dependencies
          run: dart pub get

        - name: Analyze
          run: dart analyze

        - name: Run tests
          run: dart test

