name: pana

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
  DART_VERSION: 3.5.0   

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
        
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package_panas:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        pkg: [athena_migrate, athena_mysql, athena_postgres, athena_sql, athena_utils]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_VERSION }}
      - name: Activate Melos
        run: dart pub global activate melos
      - name: Install Dependencies
        run: melos bs
      - uses: flutterings/dart-package-analyzer@v1
        # set an id for the current step
        id: analysis

      # You can then use this id to retrieve the outputs in the next steps.
      # The following step shows how to exit the workflow with an error if the total score in percentage is below 50:
      - name: Check scores
        env:
          # NB: "analysis" is the id set above. Replace it with the one you used if different.
          TOTAL: ${{ steps.analysis.outputs.total }}
          TOTAL_MAX: ${{ steps.analysis.outputs.total_max }}
        run: |
          PERCENTAGE=$(( $TOTAL * 100 / $TOTAL_MAX ))
          if (( $PERCENTAGE < 50 ))
          then
            echo Score too low!
            exit 1
          fi