name: Publish
on:
  push:
    branches:
      - master

concurrency:
  group: "publish"
  cancel-in-progress: true
env:
  DART_VERSION: 3.5.0

jobs:
  publish_alpha:
    if: |
      startsWith(github.event.head_commit.message, 'feat')
      || startsWith(github.event.head_commit.message, 'fix')
      || startsWith(github.event.head_commit.message, 'bug')
      || startsWith(github.event.head_commit.message, 'perf')
      || startsWith(github.event.head_commit.message, 'refactor')
      || startsWith(github.event.head_commit.message, 'revert')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
           fetch-depth: 0 # we need tags for melos, no better option ATM but check https://github.com/actions/checkout/issues/701
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_VERSION }}
      - uses: bluefireteam/melos-action@v3
        with:
          publish: true
          tag: true
          git-email: github-actions@github.com
          git-name: github-actions
      - name: Push tags
        uses: CasperWA/push-protected@v2
        with:
          token: ${{ secrets.ATHENA_PAT }}
          tags: true
          branch: master