name: Publish
on:
  push:
    branches:
      - master

concurrency:
  group: "publish"
  cancel-in-progress: true
env:
  DART_VERSION: 2.19.0

jobs:
  publish_alpha:
    if: |
      startsWith(github.event.head_commit.message, 'feat')
      || startsWith(github.event.head_commit.message, 'fix')
      || startsWith(github.event.head_commit.message, 'bug')
      || startsWith(github.event.head_commit.message, 'perf')
      || startsWith(github.event.head_commit.message, 'refactor')
      || startsWith(github.event.head_commit.message, 'revert')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with: 
           fetch-depth: 0 # we need tags for melos, no better option ATM but check https://github.com/actions/checkout/issues/701
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: ${{ env.DART_VERSION }}
      - name: Activate melos
        run: |
          echo "$HOME/.pub-cache/bin" >> $GITHUB_PATH
          dart pub global activate melos
      - name: Bootstrap melos
        run: melos bs
      - name: Configure git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - run: melos version --yes
      - run: melos run cache-source
      - name: Setup Pub Credentials
        shell: bash
        env:
          CREDENTIALS_JSON: ${{ secrets.PUB_CREDENTIALS }}
        run: |
          mkdir -p $XDG_CONFIG_HOME/dart/
          echo $CREDENTIALS_JSON > $XDG_CONFIG_HOME/dart/pub-credentials.json
      - run: melos publish --yes --dry-run
      - run: melos publish --yes --no-dry-run --git-tag-version
        continue-on-error: true
      - name: Push back version bumps
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
          tags: true