name: Tag and start release
on:
  push:
    branches: [master]

jobs:
  publish-packages:
    name: Create tags for release
    permissions:
      actions: write
      contents: write
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, 'chore(release)')
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dart-lang/setup-dart@v1
      - uses: bluefireteam/melos-action@v3
        with:
          tag: true
          git-email: github-actions@github.com
          git-name: github-actions
      - run: |
          melos exec -c 1 --no-published --no-private --order-dependents -- \
          gh workflow run release-publish.yml \
          --ref \$MELOS_PACKAGE_NAME-v\$MELOS_PACKAGE_VERSION
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
