name: Publish packages
on:
  # Enable to also publish, when pushing a tag
  #push:
  #  tags:
  #    - '*'
  workflow_dispatch:

env:
    DART_VERSION: 3.5.0
jobs:
  publish-packages:
    name: Publish packages
    permissions:
      contents: write
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dart-lang/setup-dart@v1
      - uses: bluefireteam/melos-action@v3
        with:
          publish: true
          git-email: github-actions@github.com
          git-name: github-actions